title: MeDIC
logo: logo.png
favicon: favicon.ico
apple_touch_icon: logo.png
accent_image: /imgs/pexels-roman-odintsov-4871011.jpg
description: Metabolomic Dashboard for Interpretable Classification
remote_theme: hydecorp/hydejack@v9.1.6
plugins:
- jekyll-remote-theme
- jekyll-include-cache
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
menu:
  - title: About
    url:   /about/
  - title: Installation
    url:   /installation/
  - title: Home
    url:   /home/
  - title: Splits
    url:   /splits/
  - title: Machine Learning
    url: /ml/
  - title: Results
    url: /results/
  - title: Results aggregated
    url: /resultsagg/
  - title: Implementation
    url: /implementation/

