markdown: kramdown
title: MeDIC
logo: logo.png
favicon: favicon.ico
apple_touch_icon: logo.png
accent_image: /imgs/gradient2.png
accent_color: rgb(174, 174, 174)
tagline: Documentation website
invert_sidebar: false

remote_theme: hydecorp/hydejack@v9.1.6
plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-default-layout
- jekyll-feed
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-titles-from-headings
- jekyll-last-modified-at

hydejack:
  no_search: false


kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  parse_block_html: true

menu:
  - title: About
    url: /index
  - title: Installation
    url: /installation
  - title: Interface tabs
    url: #
    sub :
      - title: Home tab
        url: /home
  - title: Splits tab
    url: /splits
  - title: Machine Learning tab
    url: /ml
  - title: Results tab
    url: /results
  - title: Results aggregated tab
    url: /resultsagg
  - title: Implementation
    url: /implementation
  - title: View on github
    url: https://github.com/ElinaFF/MeDIC

