markdown: kramdown
title: MeDIC
logo: logo.png
favicon: favicon.ico
apple_touch_icon: logo.png
accent_image: /imgs/gradient1.png
accent_color: rgb(174, 174, 174)
tagline: Documentation website

remote_theme: hydecorp/hydejack@v9.1.6
plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-default-layout
- jekyll-feed
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-titles-from-headings
- jekyll-last-modified-at

hydejack:
  no_search: false


kramdown:
  math_engine: mathjax
  math_engine_opts: {}

menu:
  - title: View on github
    url:   https://github.com/ElinaFF/MeDIC
  - title: Installation
    url:   /installation_doc
  - title: Home
    url:   /home
  - title: Splits
    url:   /splits
  - title: Machine Learning
    url: /ml
  - title: Results
    url: /results
  - title: Results aggregated
    url: /resultsagg
  - title: Implementation
    url: /implementation

