name: launcher test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REPO: https://ElinaFF:${{secrets.GITHUB_TOKEN}}@github.com/ElinaFF/MetaboDashboard.git

jobs:
  with_source_code:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: launch launcher.py
      run: |
        python launcher.py --no-launch

