# Thanks to Cluster (https://stackoverflow.com/questions/35445186/can-github-automatically-merge-branches)

name: Merge master in branch cloneForInstallation

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  REPO: https://ElinaFF:${{secrets.GITHUB_TOKEN}}@github.com/ElinaFF/MetaboDashboard.git

  TARGET_BRANCH: cloneForInstallation

  MASTER_BRANCH: origin/master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Clone github repository
        run: |
          git clone ${{env.REPO}} tmp
          cd tmp
          git config user.name "Automerge Bot"
          git config user.email "bot@example.com"

      - name: Re-create target branch
        run: |
          git branch -D ${{env.TARGET_BRANCH}}
          git branch ${{env.TARGET_BRANCH}}

      - name: Delete launcher.py, workflows, tests and root init
        run: |
          cd tmp
          git checkout ${{env.TARGET_BRANCH}}
          rm -f launcher.py
          rm -rf .github/
          rm -rf test/
          rm -f __init__.py
          git add .
          git commit -m "Remove necessary files"
          git push